import { Skin } from '../types';
import { ALL_ACHIEVEMENTS } from '../data/storyData';

export const GAME_CONSTANTS = {
  // Canvas dimensions (virtual base resolution)
  BASE_WIDTH: 800,
  BASE_HEIGHT: 450,

  // Ground level relative to bottom
  GROUND_Y: 370,

  // Player physics
  PLAYER_X: 120,
  PLAYER_WIDTH: 36,
  PLAYER_HEIGHT: 44,
  GRAVITY: 0.82,
  JUMP_FORCE: -14.2,
  AIR_CONTROL: 0.98,
  RUN_BOUNCE_SPEED: 0.22,

  // Speed and difficulty
  INITIAL_SPEED: 6.2,
  MAX_SPEED: 13.8,
  SPEED_ACCELERATION: 0.04,
  MIN_OBSTACLE_SPACING: 240,
  MAX_OBSTACLE_SPACING: 420,

  // Combo system
  COMBO_TIMEOUT_MS: 3800,
  MAX_COMBO_MULTIPLIER: 8,

  // Collectible values
  COIN_VALUES: {
    NORMAL: 10,
    RARE: 50,
    PERFECT: 100,
    MEMORY_SHARD: 150,
    CORRUPTED_ANOMALY: 200,
  },

  COIN_REWARDS: {
    NORMAL: 1,
    RARE: 5,
    PERFECT: 15,
    MEMORY_SHARD: 20,
    CORRUPTED_ANOMALY: 25,
  },

  // Score intervals
  SURVIVAL_SCORE_PER_SEC: 15,
  OBSTACLE_DODGE_SCORE: 25,
  NEAR_MISS_BONUS_SCORE: 40,
  NEAR_MISS_DISTANCE: 28,

  // Screen shake
  MAX_SHAKE_INTENSITY: 12,
  SHAKE_DECAY: 0.88,

  // Daily challenge defaults
  DAILY_REWARD_COINS: 120,

  // Themes by duration (seconds)
  THEME_THRESHOLDS: {
    DAY: 0,
    SUNSET: 25,
    NIGHT: 55,
    NEON: 90,
  },
} as const;

export const AVAILABLE_SKINS: Skin[] = [
  {
    id: 'default',
    name: 'The Original',
    description: 'Original Runner identity with standard quantum stabilization.',
    cost: 0,
    unlockedByDefault: true,
    colors: {
      primary: '#06b6d4',
      secondary: '#0891b2',
      accent: '#67e8f9',
      glow: 'rgba(6, 182, 212, 0.45)',
      trail: 'rgba(6, 182, 212, 0.25)',
    },
  },
  {
    id: 'night_runner',
    name: 'Night Runner',
    description: 'Dark tactical stealth suit built to survive after the sun disappeared.',
    cost: 12000,
    colors: {
      primary: '#1e293b',
      secondary: '#0f172a',
      accent: '#38bdf8',
      glow: 'rgba(56, 189, 248, 0.45)',
      trail: 'rgba(56, 189, 248, 0.25)',
    },
  },
  {
    id: 'last_survivor',
    name: 'Last Survivor',
    description: 'Worn survivor gear and reinforced straps of someone who never gave up.',
    cost: 0,
    colors: {
      primary: '#78716c',
      secondary: '#44403c',
      accent: '#f59e0b',
      glow: 'rgba(245, 158, 11, 0.4)',
      trail: 'rgba(245, 158, 11, 0.2)',
    },
  },
  {
    id: 'chrome_runner',
    name: 'Chrome Runner',
    description: 'Polished chrome futuristic alloy and mechanical joint struts.',
    cost: 0,
    colors: {
      primary: '#cbd5e1',
      secondary: '#94a3b8',
      accent: '#f8fafc',
      glow: 'rgba(248, 250, 252, 0.65)',
      trail: 'rgba(203, 213, 225, 0.35)',
    },
  },
  {
    id: 'null_skin',
    name: 'NULL',
    description: 'Light-absorbing matte-black void that defies ordinary geometry.',
    cost: 0,
    colors: {
      primary: '#09090b',
      secondary: '#020617',
      accent: '#a855f7',
      glow: 'rgba(168, 85, 247, 0.4)',
      trail: 'rgba(9, 9, 11, 0.6)',
    },
  },
  {
    id: 'artificial_angel',
    name: 'Artificial Angel',
    description: 'Ceramic celestial plating and engineered kinetic wing structures.',
    cost: 0,
    colors: {
      primary: '#f8fafc',
      secondary: '#d97706',
      accent: '#fef08a',
      glow: 'rgba(254, 240, 138, 0.6)',
      trail: 'rgba(254, 240, 138, 0.35)',
    },
  },
  {
    id: 'fracture',
    name: 'Fracture',
    description: 'Fractured anatomy split across shifting dimensional planes.',
    cost: 0,
    colors: {
      primary: '#6366f1',
      secondary: '#4338ca',
      accent: '#22d3ee',
      glow: 'rgba(34, 211, 238, 0.5)',
      trail: 'rgba(99, 102, 241, 0.3)',
    },
  },
  {
    id: 'iron_witness',
    name: 'Iron Witness',
    description: 'Heavy industrial blast armor built to remember what was lost.',
    cost: 0,
    colors: {
      primary: '#475569',
      secondary: '#334155',
      accent: '#eab308',
      glow: 'rgba(234, 179, 8, 0.45)',
      trail: 'rgba(71, 85, 105, 0.3)',
    },
  },
  {
    id: 'memory_keeper',
    name: 'Memory Keeper',
    description: 'Layered archive robes preserving forgotten historic timelines.',
    cost: 0,
    colors: {
      primary: '#713f12',
      secondary: '#854d0e',
      accent: '#38bdf8',
      glow: 'rgba(56, 189, 248, 0.5)',
      trail: 'rgba(113, 63, 18, 0.3)',
    },
  },
  {
    id: 'void_pilgrim',
    name: 'Void Pilgrim',
    description: 'Cosmic traveler cloak drifting through endless void spaces.',
    cost: 0,
    colors: {
      primary: '#312e81',
      secondary: '#1e1b4b',
      accent: '#c084fc',
      glow: 'rgba(192, 132, 252, 0.55)',
      trail: 'rgba(49, 46, 129, 0.35)',
    },
  },
  {
    id: 'the_mirror',
    name: 'The Mirror',
    description: 'Liquid mercury reflection revealing alternate versions of you.',
    cost: 0,
    colors: {
      primary: '#e2e8f0',
      secondary: '#64748b',
      accent: '#f43f5e',
      glow: 'rgba(244, 63, 94, 0.5)',
      trail: 'rgba(226, 232, 240, 0.3)',
    },
  },
  {
    id: 'beyond_the_blink',
    name: 'Beyond The Blink',
    description: 'The terrifying form that exists between closed eyelids.',
    cost: 0,
    colors: {
      primary: '#030712',
      secondary: '#111827',
      accent: '#ef4444',
      glow: 'rgba(239, 68, 68, 0.65)',
      trail: 'rgba(239, 68, 68, 0.3)',
    },
  },
  {
    id: 'ash_runner',
    name: 'Ash Runner',
    description: 'Charcoal survival fabric smoldering with embers from the old world.',
    cost: 15000,
    colors: {
      primary: '#292524',
      secondary: '#1c1917',
      accent: '#f97316',
      glow: 'rgba(249, 115, 22, 0.55)',
      trail: 'rgba(249, 115, 22, 0.3)',
    },
  },
  {
    id: 'white_noise',
    name: 'White Noise',
    description: 'Translucent synthetic frequencies and television broadcast static.',
    cost: 0,
    colors: {
      primary: '#f1f5f9',
      secondary: '#64748b',
      accent: '#0284c7',
      glow: 'rgba(2, 132, 199, 0.5)',
      trail: 'rgba(241, 245, 249, 0.3)',
    },
  },
  {
    id: 'redacted',
    name: 'Redacted',
    description: 'Black censor bars masking a profile erased from history.',
    cost: 0,
    colors: {
      primary: '#18181b',
      secondary: '#09090b',
      accent: '#facc15',
      glow: 'rgba(250, 204, 21, 0.45)',
      trail: 'rgba(24, 24, 27, 0.3)',
    },
  },
  {
    id: 'clockwork',
    name: 'Clockwork',
    description: 'Exposed brass cogs, balance wheels, and an endless ticking heart.',
    cost: 0,
    colors: {
      primary: '#b45309',
      secondary: '#78350f',
      accent: '#fbbf24',
      glow: 'rgba(251, 191, 36, 0.55)',
      trail: 'rgba(180, 83, 9, 0.3)',
    },
  },
  {
    id: 'deep_sea',
    name: 'Deep Sea',
    description: 'Heavy atmospheric diving suit designed for crushing depths.',
    cost: 35000,
    colors: {
      primary: '#0f766e',
      secondary: '#134e4a',
      accent: '#2dd4bf',
      glow: 'rgba(45, 212, 191, 0.55)',
      trail: 'rgba(15, 118, 110, 0.3)',
    },
  },
  {
    id: 'red_shift',
    name: 'Red Shift',
    description: 'Relativistic Doppler displacement tearing through speed barriers.',
    cost: 0,
    colors: {
      primary: '#dc2626',
      secondary: '#991b1b',
      accent: '#fda4af',
      glow: 'rgba(220, 38, 38, 0.65)',
      trail: 'rgba(220, 38, 38, 0.35)',
    },
  },
  {
    id: 'the_archivist',
    name: 'The Archivist',
    description: 'Formal archivist coat bearing forgotten scriptures and tokens.',
    cost: 0,
    colors: {
      primary: '#92400e',
      secondary: '#78350f',
      accent: '#fde047',
      glow: 'rgba(253, 224, 71, 0.45)',
      trail: 'rgba(146, 64, 14, 0.3)',
    },
  },
  {
    id: 'broken_halo',
    name: 'Broken Halo',
    description: 'Shattered mechanical wings and a fallen circular halo crown.',
    cost: 0,
    colors: {
      primary: '#e2e8f0',
      secondary: '#a1a1aa',
      accent: '#fbbf24',
      glow: 'rgba(251, 191, 36, 0.55)',
      trail: 'rgba(226, 232, 240, 0.3)',
    },
  },
  {
    id: 'the_drifter',
    name: 'The Drifter',
    description: 'Layered traveler poncho and survival gear from an unknown world.',
    cost: 30000,
    colors: {
      primary: '#a8a29e',
      secondary: '#57534e',
      accent: '#fb923c',
      glow: 'rgba(251, 146, 60, 0.5)',
      trail: 'rgba(168, 162, 158, 0.3)',
    },
  },
  {
    id: 'static_skin',
    name: 'Static',
    description: 'Torn raster scanlines and corrupted display buffers.',
    cost: 0,
    colors: {
      primary: '#334155',
      secondary: '#1e293b',
      accent: '#f43f5e',
      glow: 'rgba(244, 63, 94, 0.5)',
      trail: 'rgba(51, 65, 85, 0.3)',
    },
  },
  {
    id: 'the_last_memory',
    name: 'The Last Memory',
    description: 'Ethereal spectral remnants fading into timeless vapor.',
    cost: 0,
    colors: {
      primary: '#38bdf8',
      secondary: '#0284c7',
      accent: '#bae6fd',
      glow: 'rgba(56, 189, 248, 0.65)',
      trail: 'rgba(56, 189, 248, 0.35)',
    },
  },
  {
    id: 'paradox',
    name: 'Paradox',
    description: 'Impossible dual-state existence that defies timeline consistency.',
    cost: 0,
    colors: {
      primary: '#4c1d95',
      secondary: '#2e1065',
      accent: '#38bdf8',
      glow: 'rgba(56, 189, 248, 0.65)',
      trail: 'rgba(76, 29, 149, 0.35)',
    },
  },
  {
    id: 'rust_nomad',
    name: 'Rust Nomad',
    description: 'Patchwork scrap leather poncho and scavenged copper rebreather.',
    cost: 0,
    colors: {
      primary: '#78350f',
      secondary: '#451a03',
      accent: '#d97706',
      glow: 'rgba(217, 119, 6, 0.45)',
      trail: 'rgba(120, 53, 15, 0.3)',
    },
  },
  {
    id: 'cyber_courier',
    name: 'Neo Courier',
    description: 'Aerodynamic messenger cowl and carbon-fiber courier rig.',
    cost: 0,
    colors: {
      primary: '#0ea5e9',
      secondary: '#0369a1',
      accent: '#38bdf8',
      glow: 'rgba(14, 165, 233, 0.55)',
      trail: 'rgba(56, 189, 248, 0.35)',
    },
  },
  {
    id: 'void_diver',
    name: 'Void Diver',
    description: 'Deep-vacuum atmospheric helm with umbilical life-support harness.',
    cost: 0,
    colors: {
      primary: '#042f2e',
      secondary: '#134e4a',
      accent: '#14b8a6',
      glow: 'rgba(20, 184, 166, 0.5)',
      trail: 'rgba(19, 78, 74, 0.3)',
    },
  },
  {
    id: 'glitch_weaver',
    name: 'Glitch Weaver',
    description: 'Deconstructed techwear parka with floating holographic ribbons.',
    cost: 0,
    colors: {
      primary: '#475569',
      secondary: '#1e293b',
      accent: '#a855f7',
      glow: 'rgba(168, 85, 247, 0.55)',
      trail: 'rgba(147, 51, 234, 0.3)',
    },
  },
  {
    id: 'aegis_vanguard',
    name: 'Aegis Vanguard',
    description: 'Hardlight ballistic barrier armor and tactical HUD visor.',
    cost: 0,
    colors: {
      primary: '#1e293b',
      secondary: '#0f172a',
      accent: '#3b82f6',
      glow: 'rgba(59, 130, 246, 0.6)',
      trail: 'rgba(30, 41, 59, 0.35)',
    },
  },
  {
    id: 'solar_nomad',
    name: 'Solar Nomad',
    description: 'Billowing dune cloak, brass astrolabe pack, and polarized sand-goggles.',
    cost: 0,
    colors: {
      primary: '#b45309',
      secondary: '#78350f',
      accent: '#f59e0b',
      glow: 'rgba(245, 158, 11, 0.55)',
      trail: 'rgba(180, 83, 9, 0.3)',
    },
  },
  {
    id: 'chrono_detective',
    name: 'Chrono Investigator',
    description: 'Noir investigator trenchcoat adorned with glowing timeline pins.',
    cost: 0,
    colors: {
      primary: '#334155',
      secondary: '#1e293b',
      accent: '#e2e8f0',
      glow: 'rgba(226, 232, 240, 0.45)',
      trail: 'rgba(51, 65, 85, 0.3)',
    },
  },
  {
    id: 'phantom_ronin',
    name: 'Phantom Ronin',
    description: 'Lacquered cyber kasa straw hat, haori cloak, and kinetic blade scabbard.',
    cost: 0,
    colors: {
      primary: '#0f172a',
      secondary: '#020617',
      accent: '#ef4444',
      glow: 'rgba(239, 68, 68, 0.6)',
      trail: 'rgba(15, 23, 42, 0.4)',
    },
  },
  {
    id: 'neon_aristocrat',
    name: 'Night Aristocrat',
    description: 'High-collared midnight velvet tailcoat, silver monocle, and cane.',
    cost: 0,
    colors: {
      primary: '#1e1b4b',
      secondary: '#0f0e26',
      accent: '#c084fc',
      glow: 'rgba(192, 132, 252, 0.55)',
      trail: 'rgba(30, 27, 75, 0.35)',
    },
  },
  {
    id: 'astral_sovereign',
    name: 'Astral Sovereign',
    description: 'Imperial starlight mantle, celestial crown, and orbiting cosmic rings.',
    cost: 0,
    colors: {
      primary: '#312e81',
      secondary: '#1e1b4b',
      accent: '#fbbf24',
      glow: 'rgba(251, 191, 36, 0.65)',
      trail: 'rgba(49, 46, 129, 0.4)',
    },
  },
  // Legacy skins for full backwards compatibility
  {
    id: 'neon',
    name: 'Neon Pulse',
    description: 'Vibrant synthwave aesthetic with charged magenta overdrive.',
    cost: 150,
    colors: {
      primary: '#ec4899',
      secondary: '#f43f5e',
      accent: '#facc15',
      glow: 'rgba(236, 72, 153, 0.55)',
      trail: 'rgba(236, 72, 153, 0.3)',
    },
  },
  {
    id: 'robot',
    name: 'Chrono Bot',
    description: 'Precision-machined titanium alloy with high-torque micro-thrusters.',
    cost: 300,
    colors: {
      primary: '#3b82f6',
      secondary: '#1d4ed8',
      accent: '#f97316',
      glow: 'rgba(59, 130, 246, 0.5)',
      trail: 'rgba(59, 130, 246, 0.25)',
    },
  },
  {
    id: 'ghost',
    name: 'Void Phantom',
    description: 'Semi-transparent spectral anomaly phasing between realities.',
    cost: 500,
    colors: {
      primary: '#a855f7',
      secondary: '#7e22ce',
      accent: '#e9d5ff',
      glow: 'rgba(168, 85, 247, 0.6)',
      trail: 'rgba(168, 85, 247, 0.35)',
    },
  },
  {
    id: 'pixel',
    name: 'Retro 8-Bit',
    description: 'Nostalgic arcade green matrix phosphor CRT styling.',
    cost: 750,
    colors: {
      primary: '#22c55e',
      secondary: '#15803d',
      accent: '#86efac',
      glow: 'rgba(34, 197, 94, 0.5)',
      trail: 'rgba(34, 197, 94, 0.3)',
    },
  },
  {
    id: 'golden',
    name: 'Solar King',
    description: 'Forged from celestial stardust. The ultimate flex of mastery.',
    cost: 1200,
    colors: {
      primary: '#eab308',
      secondary: '#ca8a04',
      accent: '#fef08a',
      glow: 'rgba(234, 179, 8, 0.65)',
      trail: 'rgba(234, 179, 8, 0.4)',
    },
  },
];

export const INITIAL_ACHIEVEMENTS = ALL_ACHIEVEMENTS;
